### ISSUE TITLE
Cannot able to load from disk

### ISSUE THREAD

**Issue by iabhiyaan** [francmarin98/vitesse-dark-theme#1]
Gives error while loading from disk: 
Fail to load plugin descriptor from file

**Comment by francmarin98** [comment]
That is totally true and the main reason is because there is nothing at the moment hehe.
I was going to create the theme but I was seeing that they were going to release a new UI so I left it on pause.

But you can rest assured that in a few days you will have something functional, today they gave me access to the new UI :D

**Comment by iabhiyaan** [comment]
Cant wait to use the theme 😀
